---
platform: linux
image: docker:///cloudfoundry/lattice-pipeline
inputs:
- name: lattice-ci
- name: lattice
- name: deploy-terraform-gce
run:
  path: lattice-ci/tasks/cleanup-deploy-terraform-gce/run.sh
