---
platform: linux
image: docker:///cloudfoundry/lattice-bosh
inputs:
- name: lattice
run:
  path: lattice/concourse/tasks/deploy-concourse/run.sh
params:
  BOSH_TARGET: some-target
  BOSH_PASSWORD: some-bosh-password
  CONCOURSE_USER: some-concourse-user
  CONCOURSE_PASSWORD: some-concourse-password
  CONCOURSE_VERSION: some-concourse-version
  GARDEN_LINUX_VERSION: some-garden-version
  CLOUDFORMATION_STACK_NAME: some-stack-name
  AWS_DEFAULT_REGION: some-region
  AWS_ACCESS_KEY_ID: some-access-key-id
  AWS_SECRET_ACCESS_KEY: some-secret-access-key
