---
platform: linux
image: docker:///cloudfoundry/lattice-pipeline
inputs:
- name: lattice-ci
- name: lattice
- name: lattice-tar-build
run:
  path: lattice-ci/tasks/deploy-terraform-gce/run.sh
params:
  GCE_SSH_PRIVATE_KEY: some-ssh-private-key
  GCE_PROJECT_NAME: some-project-name
  GCE_ACCOUNT_FILE_JSON: some-account-file-json
