---
name: concourse

director_uuid: BOSH-UUID

atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: atc
  password: CONCOURSE-PASSWORD

availability_zone: &az us-east-1a

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.16.0/20
        reserved: [10.0.16.2 - 10.0.16.9]
        static:
          - &discovery_static_ip 10.0.16.10
        dns: [10.0.0.2]
        gateway: 10.0.16.1
        cloud_properties:
          security_groups: [SECURITY-GROUP-NAME]
          subnet: PRIVATE-SUBNET-ID

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk: 1024
    templates:
      - {release: concourse, name: consul-agent}
    networks:
      - name: concourse
        static_ips: [*discovery_static_ip]
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: tsa}
      - {release: concourse, name: atc}
    networks: [{name: concourse}]
    properties:
      atc:
        publicly_viewable: true
        basic_auth_username: CONCOURSE-USERNAME
        basic_auth_password: CONCOURSE-PASSWORD
        postgresql:
          database: *atc-db-name
          role: *atc-db-role
      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}
      tsa:
        host_key: TSA-PRIVATE-KEY
        authorized_keys: [VSPHERE-WORKER-PUBLIC-KEY]

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk_pool: database
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: postgresql}
    networks: [{name: concourse}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]
      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}

  - name: worker
    instances: 3
    resource_pool: workers
    templates:
      - {release: concourse, name: consul-agent}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}
    networks: [{name: concourse}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
      consul:
        agent:
          servers: {lan: [*discovery_static_ip]}
      groundcrew:
        tsa:
          host_public_key: TSA-PUBLIC-KEY
        resource_types:
        - type: archive
          image: /var/vcap/packages/archive_resource
        - type: cf
          image: /var/vcap/packages/cf_resource
        - type: docker-image
          image: /var/vcap/packages/docker_image_resource
        - type: git
          image: /var/vcap/packages/git_resource
        - type: s3
          image: docker:///krobertson/s3-resource
        - type: semver
          image: /var/vcap/packages/semver_resource
        - type: time
          image: /var/vcap/packages/time_resource
        - type: tracker
          image: /var/vcap/packages/tracker_resource
        - type: pool
          image: /var/vcap/packages/pool_resource
        - type: vagrant-cloud
          image: /var/vcap/packages/vagrant_cloud_resource
        - type: github-release
          image: /var/vcap/packages/github_release_resource
        - type: bosh-io-release
          image: /var/vcap/packages/bosh_io_release_resource
        - type: bosh-io-stemcell
          image: /var/vcap/packages/bosh_io_stemcell_resource
        - type: bosh-deployment
          image: /var/vcap/packages/bosh_deployment_resource

disk_pools:
  - name: database
    disk_size: 10240
    cloud_properties:
      type: gp2

resource_pools:
  - name: web
    network: concourse
    stemcell: &stemcell
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az
      elbs: [ELB-NAME]

  - name: discovery
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: databases
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.medium
      availability_zone: *az

  - name: workers
    network: concourse
    stemcell: *stemcell
    cloud_properties:
      instance_type: m3.large
      availability_zone: *az
      ephemeral_disk:
        size: 100000 # in MB
        type: gp2

compilation:
  workers: 3
  network: concourse
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: c4.large
    availability_zone: *az
    ephemeral_disk:
      size: 30000 # in MB
      type: gp2

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
