---
platform: linux
image: docker:///cloudfoundry/lattice-ci
inputs:
- name: lattice-ci
- name: lattice-release
- name: lattice-tgz
- name: vagrant-box-version
- name: terraform-ami-metadata
run:
  path: lattice-ci/tasks/build-bundle/run.sh
