---
platform: linux
image: docker:///cloudfoundry/lattice-pipeline
inputs:
- name: lattice-ci
- name: lattice
run:
  path: lattice-ci/tasks/unit-test-cell-helper/run.sh
params:
  CELL_HELPER: some-cell-helper
