---
name: micro-bosh-director-$ENVIRONMENT_NAME

releases:
- name: bosh
  url: $BOSH_DIRECTOR_RELEASE_URL
  sha1: $BOSH_DIRECTOR_RELEASE_SHA
- name: bosh-aws-cpi
  url: $BOSH_CPI_RELEASE_URL
  sha1: $BOSH_CPI_RELEASE_SHA

resource_pools:
- name: default
  network: private
  stemcell:
    url: $BOSH_STEMCELL_URL
    sha1: $BOSH_STEMCELL_SHA
  cloud_properties:
    instance_type: m3.large
    availability_zone: $AVAILABILITY_ZONE
    ephemeral_disk:
        size: 25000
        type: "gp2"

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    dns: [8.8.8.8]
    gateway: 10.0.0.1
    cloud_properties:
      subnet: $PRIVATE_SUBNET_ID
- name: public
  type: vip

disk_pools:
- name: disks
  disk_size: 25_000
  cloud_properties: {type: gp2}


jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: cpi, release: bosh-aws-cpi}

  resource_pool: default
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [10.0.0.7]
    default: [dns, gateway]
  - name: public
    static_ips: [$ELASTIC_IP]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: $BOSH_PASSWORD

    redis:
      listen_addresss: 127.0.0.1
      address: 127.0.0.1
      password: $BOSH_PASSWORD

    postgres: &db
      host: 127.0.0.1
      user: postgres
      password: $BOSH_PASSWORD
      database: bosh
      adapter: postgres

    registry:
      address: 10.0.0.7
      host: 10.0.0.7
      db: *db
      http: {user: admin, password: $BOSH_PASSWORD, port: 25777}
      username: admin
      password: $BOSH_PASSWORD
      port: 25777

    blobstore:
      address: 10.0.0.7
      port: 25250
      provider: dav
      director: {user: director, password: $BOSH_PASSWORD}
      agent: {user: agent, password: $BOSH_PASSWORD}

    director:
      address: 127.0.0.1
      name: bosh-director
      db: *db
      cpi_job: cpi
      max_threads: 10

    hm:
      http: {user: hm, password: $BOSH_PASSWORD}
      director_account: {user: admin, password: $BOSH_PASSWORD}
      resurrector_enabled: true

    aws: &aws
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      default_key_name: $KEY_NAME
      default_security_groups: [$SECURITY_GROUP_NAME]
      region: us-east-1

    agent: {mbus: "nats://nats:$BOSH_PASSWORD@10.0.0.7:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]


cloud_provider:
  template: {name: cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: $ELASTIC_IP
    port: 22
    user: vcap
    private_key: $PRIVATE_KEY_PATH

  registry: &registry
    username: admin
    password: $BOSH_PASSWORD
    port: 6901
    host: localhost

  mbus: https://nats:$BOSH_PASSWORD@$ELASTIC_IP:6868

  properties:
    aws: *aws
    agent: {mbus: "https://nats:$BOSH_PASSWORD@0.0.0.0:6868"}
    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp

