---
resources:
  - name: lattice-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice-ci.git
      branch: master
  - name: lattice-website
    type: git
    source:
      uri: git@github.com:pivotal-cf-experimental/lattice-website
      branch: master
      private_key: {{github-ssh-key}}
  - name: lattice-ci-image-changes
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice-ci.git
      branch: master
      paths: [Dockerfile]
  - name: lattice-ci-image
    type: docker-image
    source:
      repository: cloudfoundry/lattice-ci
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
  - name: concourse-release
    type: github-release
    source:
      repository: concourse
      user: concourse
  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: concourse-deployment
    type: bosh-deployment
    source:
      target: {{concourse-bosh-target}}
      username: admin
      password: {{concourse-bosh-password}}
      deployment: concourse-test

jobs:
  - name: deploy-lattice-website
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-website
    - task: deploy-lattice-website
      file: lattice-ci/tasks/deploy-lattice-website/task.yml
      config:
        params:
          GITHUB_SSH_KEY: {{github-ssh-key}}

  - name: docker-push-lattice-ci
    plan:
    - get: lattice-ci
      resource: lattice-ci-image-changes
      trigger: true
    - put: lattice-ci-image
      params:
        build: lattice-ci
        push: true

  - name: deploy-concourse
    serial: true
    plan:
    - get: lattice-ci
    - aggregate:
      - get: stemcell
      - get: concourse-release
        params:
          globs:
          - concourse-*.tgz
          - garden-linux-*.tgz
      - task: deploy-concourse
        file: lattice-ci/tasks/deploy-concourse/task.yml
        config:
          params:
            CONCOURSE_USER: {{concourse-user}}
            CONCOURSE_PASSWORD: {{concourse-password}}
            CLOUDFORMATION_STACK_NAME: ci
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            BOSH_UUID: {{concourse-bosh-uuid}}
            BOSH_PASSWORD: {{concourse-bosh-password}}
    - put: concourse-deployment
      params:
        manifest: deploy-concourse/manifest.yml
        releases:
        - concourse-release/concourse-*.tgz
        - concourse-release/garden-linux-release-*.tgz
        stemcells:
        - stemcell/*.tgz
