resources:
  - name: lattice-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice-ci.git
      branch: master
  - name: lattice-release
    type: git
    source:
      uri: git@github.com:sclevine/lattice-release.git
      branch: master
      private_key: {{github-ssh-key}}
  - name: vagrant-image-changes
    type: git
    source:
      uri: git@github.com:sclevine/lattice-release.git
      branch: master
      private_key: {{github-ssh-key}}
      ignore_paths: [vagrant/Vagrantfile]
      paths:
      - vagrant
      - bosh
      - diego-release
      - garden-linux-release
      - cf-routing-release
      - cf-release
      - cf-lattice.yml
  - name: terraform-image-changes
    type: git
    source:
      uri: git@github.com:sclevine/lattice-release.git
      branch: master
      private_key: {{github-ssh-key}}
      ignore_paths: [terraform/aws]
      paths:
      - terraform
      - bosh
      - diego-release
      - garden-linux-release
      - cf-routing-release
      - cf-release
      - cf-lattice.yml

  - name: vagrant-box-version
    type: semver
    source:
      bucket: lattice
      key: vagrant/box-version
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
      region_name: us-west-2
  - name: vagrant-box-commit
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: vagrant/box-commit-v(.*)
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: terraform-ami-version
    type: semver
    source:
      bucket: lattice
      key: terraform/ami-version
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
      region_name: us-west-2
  - name: terraform-ami-metadata
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: terraform/ami-metadata-v(.*)
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: terraform-ami-commit
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: terraform/ami-commit-v(.*)
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

  - name: lattice-tgz
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: lattice-tgz/lattice-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-bundle-ci
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: ci/lattice-bundle-v(.*).zip
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-bundle-acceptance
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: acceptance/lattice-bundle-v(.*).zip
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-bundle-nightly
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: nightly/lattice-bundle-v(.*).zip
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

  - name: lattice-tracker
    type: tracker
    source:
      token: {{tracker-api-token}}
      project_id: "1183596"
  - name: publish-nightly-timer
    type: time
    source:
      start: 18:00 -0500
      stop: 19:00 -0500
      interval: 1h

jobs:
  - name: build-images
    serial: true
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
      - get: vagrant-image-changes
        params:
          submodules: all
      - get: terraform-image-changes
        params:
          submodules: all
      - get: vagrant-box-commit
      - get: current-vagrant-box-version
        resource: vagrant-box-version
      - get: next-vagrant-box-version
        resource: vagrant-box-version
        params:
          bump: minor
      - get: terraform-ami-commit
      - get: current-terraform-ami-version
        resource: terraform-ami-version
      - get: next-terraform-ami-version
        resource: terraform-ami-version
        params:
          bump: minor
    - aggregate:
      - task: build-vagrant-images
        file: lattice-ci/tasks/build-vagrant-images/task.yml
        config:
          params:
            atlas_token: {{atlas-api-token}}
      - task: build-terraform-images
        file: lattice-ci/tasks/build-terraform-images/task.yml
        config:
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
    - put: vagrant-box-commit
      params:
        from: build-vagrant-images/box-commit-v(.*)
        to: /vagrant/
    - put: vagrant-box-version
      params:
        file: updated-vagrant-box-version/number
    - put: terraform-ami-metadata
      params:
        from: build-terraform-images/ami-metadata-v(.*)
        to: /terraform/
    - put: terraform-ami-commit
      params:
        from: build-terraform-images/ami-commit-v(.*)
        to: /terraform/
    - put: terraform-ami-version
      params:
        file: updated-terraform-ami-version/number

  - name: unit-test-ltc
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        params:
          submodules: all
        passed: [build-images]
      - get: vagrant-box-version
        passed: [build-images]
      - get: terraform-ami-metadata
        passed: [build-images]
    - task: unit-test
      file: lattice-ci/tasks/unit-test/task.yml
      config:
        params:
          PACKAGE: github.com/cloudfoundry-incubator/lattice/ltc

  - name: unit-test-cell-helpers
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        params:
          submodules: all
        passed: [build-images]
      - get: vagrant-box-version
        passed: [build-images]
      - get: terraform-ami-metadata
        passed: [build-images]
    - task: unit-test
      file: lattice-ci/tasks/unit-test/task.yml
      config:
        params:
          PACKAGE: github.com/cloudfoundry-incubator/lattice/cell-helpers

  - name: gofmt
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        params:
          submodules: [src/github.com/cloudfoundry-incubator/lattice]
      - get: vagrant-box-version
        passed: [build-images]
      - get: terraform-ami-metadata
        passed: [build-images]
    - task: unit-test
      file: lattice-ci/tasks/gofmt/task.yml
      config:
        params:
          PACKAGE: github.com/cloudfoundry-incubator/lattice

  - name: compile-lattice-tgz
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        params:
          submodules: all
        passed:
        - unit-test-ltc
        - unit-test-cell-helpers
        - gofmt
      - get: vagrant-box-version
        passed:
        - unit-test-ltc
        - unit-test-cell-helpers
        - gofmt
      - get: terraform-ami-metadata
        passed:
        - unit-test-ltc
        - unit-test-cell-helpers
        - gofmt
    - task: compile-lattice-tgz
      file: lattice-ci/tasks/compile-lattice-tgz/task.yml
    - put: lattice-tgz
      params:
        from: compile-lattice-tgz/lattice-v(.*).tgz
        to: /lattice-tgz/

  - name: build-bundle
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        passed: [compile-lattice-tgz]
      - get: lattice-tgz
        passed: [compile-lattice-tgz]
      - get: vagrant-box-version
        passed: [compile-lattice-tgz]
      - get: terraform-ami-metadata
        passed: [compile-lattice-tgz]
    - task: build-bundle
      file: lattice-ci/tasks/build-bundle/task.yml
    - put: lattice-bundle-ci
      params:
        from: build-bundle/lattice-bundle-v(.*).zip
        to: /ci/

  - name: cluster-test-vagrant-aws
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        passed: [build-bundle]
      - get: lattice-tgz
        passed: [build-bundle]
      - get: lattice-bundle-ci
        passed: [build-bundle]
    do:
      - task: deploy-vagrant-aws
        file: lattice-ci/tasks/deploy-vagrant-aws/task.yml
        config:
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
      - aggregate:
        - task: cluster-test-vagrant-aws-dav
          file: lattice-ci/tasks/cluster-test-vagrant-aws-dav/task.yml
        - task: cluster-test-vagrant-aws-s3
          file: lattice-ci/tasks/cluster-test-vagrant-aws-s3/task.yml
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            AWS_REGION: {{cluster-test-aws-region}}
            AWS_BUCKET: {{cluster-test-s3-bucket-name}}
    ensure:
      - task: cleanup-deploy-vagrant-aws
        file: lattice-ci/tasks/cleanup-deploy-vagrant-aws/run.sh

  - name: cluster-test-terraform-aws
    plan:
    - aggregate:
      - get: lattice-ci
      - get: lattice-release
        trigger: true
        passed: [build-bundle]
      - get: lattice-tgz
        passed: [build-bundle]
      - get: lattice-bundle-ci
        passed: [build-bundle]
    do:
      - task: deploy-terraform-aws
        file: lattice-ci/tasks/deploy-terraform-aws/task.yml
        config:
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
      - aggregate:
        - task: cluster-test-terraform-aws-dav
          file: lattice-ci/tasks/cluster-test-terraform-aws-dav/task.yml
        - task: cluster-test-terraform-aws-s3
          file: lattice-ci/tasks/cluster-test-terraform-aws-s3/task.yml
          params:
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            AWS_REGION: {{cluster-test-aws-region}}
            AWS_BUCKET: {{cluster-test-s3-bucket-name}}
    ensure:
      - task: cleanup-deploy-terraform-aws
        file: lattice-ci/tasks/cleanup-deploy-terraform-aws/run.sh
