resources:
  - name: lattice-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice-ci.git
      branch: master
  - name: lattice-release
    type: git
    source:
      uri: git@github.com:sclevine/lattice-release.git
      branch: master
      private_key: {{github-ssh-key}}
  - name: vagrant-boxes
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: development/vagrant-boxes-v(.*).box
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-tgz
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: development/lattice-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: ltc-tgz
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: development/ltc-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}


jobs:
  - name: build-vagrant-boxes
    plan:
      - aggregate:
        - get: lattice-ci
        - get: lattice-release
          trigger: true
          params:
            submodules: all
      - task: vagrant-packer-build
        file: lattice-ci/tasks/vagrant-packer-build/task.yml
      - put: vagrant-boxes
        params:
          from: lattice-release/vagrant/vagrant-boxes-v(.*).tgz
          to: /development/

  - name: build-lattice-tar
    plan:
      - aggregate:
        - get: lattice-ci
        - get: lattice-release
          trigger: true
          params:
            submodules: all
      - task: build-lattice-tar
        file: lattice-ci/tasks/build-lattice-tar/task.yml
      - put: lattice-tgz
        params:
          from: lattice-release/lattice-v(.*).tgz
          to: /development/

  - name: build-ltc-tar
    plan:
      - aggregate:
        - get: lattice-ci
        - get: lattice-release
          trigger: true
          params:
            submodules: all
      - task: build-ltc-tar
        file: lattice-ci/tasks/build-ltc-tar/task.yml
      - put: ltc-tgz
        params:
          from: lattice-release/ltc-v(.*).tgz
          to: /development/

  - name: cluster-test-vagrant-aws
    plan:
    - aggregate:
      - get: lattice-tgz
        trigger: true
      - get: ltc-tgz
        trigger: true
      - get: vagrant-boxes
        trigger: true
        passed: [build-vagrant-boxes]
    - task: deploy-vagrant-aws-box
      file: lattice-ci/tasks/deploy-vagrant-aws-box/task.yml
      config:
        params:
          AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
          AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
          AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}

