resources:
  - name: lattice
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice.git
      branch: master

jobs:
  - name: cloudformation-for-concourse
    serial_groups: [ concourse-setup ]
    plan:
      - get: lattice
      - task: cloudformation
        file: lattice/concourse/tasks/cloudformation/task.yml
        config:
          params:
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            CLOUDFORMATION_STACK_NAME: ci
            HOSTED_ZONE_NAME: {{lattice-domain-name}}
            SSL_CERT_ARN: {{lattice-ssl-certificate-arn}}
            NAT_AMI: {{concourse-nat-ami}}

  - name: deploy-bosh-for-concourse
    serial_groups: [ concourse-setup ]
    plan:
      - get: lattice
        passed: [ cloudformation-for-concourse ]
      - task: deploy-bosh
        file: lattice/concourse/tasks/deploy-bosh/task.yml
        config:
          params:
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
            CLOUDFORMATION_STACK_NAME: ci
            KEY_NAME: {{aws-ssh-private-key-name}}
            PRIVATE_KEY: {{aws-ssh-private-key}}
            BOSH_PASSWORD: {{concourse-bosh-password}}

  - name: deploy-concourse
    serial_groups: [ concourse-setup ]
    plan:
      - get: lattice
      - task: deploy-concourse
        file: lattice/concourse/tasks/deploy-concourse/task.yml
        config:
          params:
            BOSH_TARGET: {{concourse-bosh-target}}
            BOSH_PASSWORD: {{concourse-bosh-password}}
            CONCOURSE_USER: {{concourse-user}}
            CONCOURSE_PASSWORD: {{concourse-password}}
            CONCOURSE_VERSION: 0.61.0
            GARDEN_LINUX_VERSION: 0.303.0
            CLOUDFORMATION_STACK_NAME: ci
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
            AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
