resources:
  - name: lattice-version-changes
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/lattice.git
      branch: master
      paths: [Version]
  - name: diego-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
      branch: master
  - name: garden-linux-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/garden-linux-release.git
      branch: master
  - name: cf-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-release.git
      branch: runtime-passed
  - name: cf-routing-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/cf-routing-release.git
      branch: release_candidate
  - name: lattice-release
    type: github-release
    source:
      user: cloudfoundry-incubator
      repository: lattice
      access_token: {{github-api-token}}
  - name: lattice-tar-build
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: build/lattice-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: ltc-tar-build
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: build/ltc-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-tar-release
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: releases/backend/lattice-v(.*).tgz
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: lattice-bundle-release
    type: s3
    source:
      bucket: lattice
      region_name: us-west-2
      regexp: releases/lattice-bundle-v(.*).zip
      private: true
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}

jobs:
  - name: unit-tests
    plan:
      - get: lattice
        resource: lattice-version-changes
        trigger: true
      - aggregate:
        - task: go-fmt-ltc
          file: lattice/concourse/tasks/go-fmt/task.yml
          config:
            params:
              GO_FMT_PATH: ltc
        - task: go-fmt-davtool
          file: lattice/concourse/tasks/go-fmt/task.yml
          config:
            params:
              GO_FMT_PATH: cell-helpers/davtool
        - task: go-fmt-s3tool
          file: lattice/concourse/tasks/go-fmt/task.yml
          config:
            params:
              GO_FMT_PATH: cell-helpers/s3tool
        - task: go-fmt-tee2metron
          file: lattice/concourse/tasks/go-fmt/task.yml
          config:
            params:
              GO_FMT_PATH: cell-helpers/tee2metron
        - task: unit-test-ltc
          file: lattice/concourse/tasks/unit-test-ltc/task.yml
        - task: unit-test-cell-helper-davtool
          file: lattice/concourse/tasks/unit-test-cell-helper/task.yml
          config:
            params:
              CELL_HELPER: davtool
        - task: unit-test-cell-helper-s3tool
          file: lattice/concourse/tasks/unit-test-cell-helper/task.yml
          config:
            params:
              CELL_HELPER: s3tool
        - task: unit-test-cell-helper-tee2metron
          file: lattice/concourse/tasks/unit-test-cell-helper/task.yml
          config:
            params:
              CELL_HELPER: tee2metron

  - name: compile
    plan:
      - aggregate:
        - get: lattice
          resource: lattice-version-changes
          trigger: true
          passed: [unit-tests]
        - get: diego-release
        - get: garden-linux-release
        - get: cf-release
        - get: cf-routing-release
      - aggregate:
        - task: compile-lattice-tar
          file: lattice/concourse/tasks/compile-lattice-tar/task.yml
          config:
            params:
              RELEASE: true
        - task: compile-ltc
          file: lattice/concourse/tasks/compile-ltc/task.yml
          config:
            params:
              RELEASE: true
      - aggregate:
        - put: lattice-tar-build
          params:
            from: lattice/build/lattice-v(.*).tgz
            to: /build/
        - put: ltc-tar-build
          params:
            from: lattice/build/ltc-v(.*).tgz
            to: /build/

  - name: cluster-test
    serial: true
    plan:
      - aggregate:
        - get: lattice
          resource: lattice-version-changes
          trigger: true
          passed: [compile]
        - get: lattice-tar-build
          passed: [compile]
        - get: ltc-tar-build
          passed: [compile]
      - aggregate:
        - do:
          - task: deploy-vagrant-aws
            file: lattice/concourse/tasks/deploy-vagrant-aws/task.yml
            config:
              params:
                AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
                IGNORE_VERSION_MISMATCH: true
          - aggregate:
            - task: cluster-test-vagrant-aws-dav
              file: lattice/concourse/tasks/cluster-test-vagrant-aws-dav/task.yml
            - task: cluster-test-vagrant-aws-s3
              file: lattice/concourse/tasks/cluster-test-vagrant-aws-s3/task.yml
              config:
                params:
                  AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                  AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                  AWS_REGION: {{cluster-test-aws-region}}
                  S3_BUCKET_NAME: {{cluster-test-s3-bucket-name}}
          ensure:
            task: cleanup-deploy-vagrant-aws
            file: lattice/concourse/tasks/cleanup-deploy-vagrant-aws/task.yml
            config:
              params:
                AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
        - do:
          - task: deploy-terraform-aws
            file: lattice/concourse/tasks/deploy-terraform-aws/task.yml
            config:
              params:
                AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
                AWS_SSH_PRIVATE_KEY_NAME: {{aws-ssh-private-key-name}}
          - aggregate:
            - task: cluster-test-terraform-aws-dav
              file: lattice/concourse/tasks/cluster-test-terraform-aws-dav/task.yml
            - task: cluster-test-terraform-aws-s3
              file: lattice/concourse/tasks/cluster-test-terraform-aws-s3/task.yml
              config:
                params:
                  AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                  AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                  AWS_REGION: {{cluster-test-aws-region}}
                  S3_BUCKET_NAME: {{cluster-test-s3-bucket-name}}
          ensure:
            task: cleanup-deploy-terraform-aws
            file: lattice/concourse/tasks/cleanup-deploy-terraform-aws/task.yml
            config:
              params:
                AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                AWS_SSH_PRIVATE_KEY: {{aws-ssh-private-key}}
                AWS_SSH_PRIVATE_KEY_NAME: {{aws-ssh-private-key-name}}
        - do:
          - task: deploy-terraform-gce
            file: lattice/concourse/tasks/deploy-terraform-gce/task.yml
            config:
              params:
                GCE_SSH_PRIVATE_KEY: {{gce-ssh-private-key}}
                GCE_PROJECT_NAME: {{gce-project-name}}
                GCE_ACCOUNT_FILE_JSON: {{gce-account-file-json}}
          - aggregate:
            - task: cluster-test-terraform-gce-dav
              file: lattice/concourse/tasks/cluster-test-terraform-gce-dav/task.yml
            - task: cluster-test-terraform-gce-s3
              file: lattice/concourse/tasks/cluster-test-terraform-gce-s3/task.yml
              config:
                params:
                  AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
                  AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
                  AWS_REGION: {{cluster-test-aws-region}}
                  S3_BUCKET_NAME: {{cluster-test-s3-bucket-name}}
          ensure:
            task: cleanup-deploy-terraform-gce
            file: lattice/concourse/tasks/cleanup-deploy-terraform-gce/task.yml

  - name: publish-release
    plan:
      - aggregate:
        - get: lattice
          resource: lattice-version-changes
          trigger: true
          passed: [cluster-test]
        - get: lattice-tar-build
          passed: [cluster-test]
        - get: ltc-tar-build
          passed: [cluster-test]
      - aggregate:
        - task: generate-terraform-templates
          file: lattice/concourse/tasks/generate-terraform-templates/task.yml
          config:
            params:
              RELEASE: true
              LATTICE_URL_BASE: http://lattice.s3.amazonaws.com/releases/backend
        - task: generate-vagrantfile
          file: lattice/concourse/tasks/generate-vagrantfile/task.yml
          config:
            params:
              RELEASE: true
              LATTICE_URL_BASE: http://lattice.s3.amazonaws.com/releases/backend
      - task: compile-lattice-bundles
        file: lattice/concourse/tasks/compile-lattice-bundles/task.yml
      - aggregate:
        - put: lattice-tar-release
          params:
            from: lattice-tar-build/lattice-v(.*).tgz
            to: /releases/backend/
        - put: lattice-tar-release
          params:
            from: lattice-tar-build/lattice-v(.*).tgz
            to: /releases/backend/lattice-latest.tgz
        - put: lattice-bundle-release
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-linux.zip
            to: /releases/
        - put: lattice-bundle-release
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-linux.zip
            to: /releases/lattice-bundle-latest-linux.zip
        - put: lattice-bundle-release
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-osx.zip
            to: /releases/
        - put: lattice-bundle-release
          params:
            from: compile-lattice-bundles/lattice-bundle-v(.*)-osx.zip
            to: /releases/lattice-bundle-latest-osx.zip
      - put: lattice-release
        params:
          name: lattice/Version
          tag: lattice/Version
          commitish: compile-lattice-bundles/commit
          body: lattice/RELEASE_NOTES.md
          globs: [compile-lattice-bundles/*.zip]
