---
platform: linux
image: docker:///cloudfoundry/lattice-pipeline
inputs:
- name: lattice-ci
- name: lattice-website
run:
  path: lattice-ci/tasks/deploy-lattice-website/run.sh
params:
  GITHUB_PRIVATE_KEY: some-private-key
