---
name: concourse-vsphere

releases:
- name: concourse
  version: latest
- name: garden-linux
  version: latest
- name: bosh-vsphere-cpi
  version: latest

resource_pools:
- name: concourse
  network: concourse
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 64000

disk_pools:
- name: db
  disk_size: 64000

networks:
- name: concourse
  type: manual
  subnets:
  - range: 10.85.28.0/24
    gateway: 10.85.28.1
    dns: [10.87.8.10, 10.87.8.11]
    cloud_properties:
      name: bloodmyst

jobs:
- name: worker
  instances: 1
  resource_pool: concourse

  templates:
  - {release: concourse, name: groundcrew}
  - {release: concourse, name: baggageclaim}
  - {release: garden-linux, name: garden}

  networks:
  - name: concourse
    static_ips: [10.85.28.5]
    default: [dns, gateway]

  properties:
    garden:
      listen_network: tcp
      listen_address: 127.0.0.1:7777
    groundcrew:
      tags: ["vsphere-linux-worker"]
      garden:
        forward_address: 127.0.0.1:7777
      baggageclaim:
        forward_address: 127.0.0.1:7788
      tsa:
        host: ci.lattice.cf
        host_public_key: CONCOURSE-TSA-PUBLIC-KEY
        private_key: LOCAL-WORKER-PRIVATE-KEY

cloud_provider:
  template: {name: cpi, release: bosh-vsphere-cpi}

  mbus: "https://mbus:mbus-password@10.85.28.5:6868"

  properties:
    vcenter:
      address: VCENTER-ADDRESS
      user: VCENTER-USERNAME
      password: VCENTER-PASSWORD
      datacenters:
        - name: pizza-boxes-dc
        vm_folder: bloodmyst
        template_folder: bloodmyst_templates
        datastore_pattern: freenas-ds
        persistent_datastore_pattern: freenas-ds
        disk_path: bloodmyst
        clusters: [pizza-boxes]
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
