---
platform: linux
image: docker:///cloudfoundry/lattice-ci
inputs:
- name: build-vagrant-prepare
run:
  path: lattice-ci/tasks/build-vagrant-images/run.sh
params:
  ATLAS_TOKEN: some-atlas-token
  REMOTE_EXECUTOR_IP: no-executor
  NAMES: some-names
