---
platform: linux
image: docker:///cloudfoundry/lattice-ci
inputs:
- name: lattice-ci
- name: lattice-release
- name: version-changes
- name: github-release
run:
  path: lattice-ci/tasks/tag-release/run.sh
params:
  GITHUB_SSH_KEY: some-github-ssh-key
